# Generated by Django 5.1.3 on 2025-03-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationstep3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationStep3',
        ),
    ]
