# Generated by Django 5.1.3 on 2025-03-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_delete_registrationstep3'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStep3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentoring', models.BooleanField(default=False)),
                ('training', models.BooleanField(default=False)),
                ('financing', models.BooleanField(default=False)),
                ('resources', models.BooleanField(default=False)),
            ],
        ),
    ]
