# Generated by Django 5.1.3 on 2025-03-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registrationstep3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationstep2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registrationstep3',
            name='id',
        ),
        migrations.AddField(
            model_name='registrationstep2',
            name='registration_step1',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.registrationstep1'),
        ),
        migrations.AddField(
            model_name='registrationstep3',
            name='registration_step1',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.registrationstep1'),
        ),
    ]
