# Generated by Django 5.1.3 on 2025-03-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_registrationstep2_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationstep3',
            name='registration_step1',
        ),
        migrations.DeleteModel(
            name='RegistrationStep2',
        ),
        migrations.DeleteModel(
            name='RegistrationStep3',
        ),
    ]
