# Generated by Django 5.1.3 on 2025-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_registrationstep3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstep1',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
