# Generated by Django 5.1.3 on 2025-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_registrationstep1_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstep2',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationstep2',
            name='project_level',
            field=models.CharField(max_length=255),
        ),
    ]
