# Generated by Django 5.1.3 on 2025-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_registrationstep2_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationstep3',
            name='financing',
        ),
        migrations.RemoveField(
            model_name='registrationstep3',
            name='mentoring',
        ),
        migrations.RemoveField(
            model_name='registrationstep3',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='registrationstep3',
            name='training',
        ),
        migrations.AddField(
            model_name='registrationstep3',
            name='choice',
            field=models.CharField(blank=True, choices=[('mentoring', 'Mentorat'), ('training', 'Formation'), ('financing', 'Financement'), ('resources', 'Ressources')], max_length=20, null=True),
        ),
    ]
