# Generated by Django 5.1.3 on 2025-03-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_remove_registrationstep3_financing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                ("phone_number", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("terms_accepted", models.BooleanField(default=False)),
                ("project_name", models.CharField(max_length=255)),
                ("project_level", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("industry", models.CharField(max_length=255)),
                ("choice", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
